spring:
  cloud:
    function:
      definition: nameModifiedProducer;wordCountModifiedProcess
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          nameModifiedProducer-out-0:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
        streams:
          bindings:
            wordCountModifiedProcess-in-0:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: com.pool.config.serdes.WordSerDe
            wordCountHandler-in-0:
              consumer:
                keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
          binder:
            configuration:
              commit.interval.ms: 2000
      bindings:
        nameModifiedProducer-out-0:
          destination: news-11-topic
        wordCountModifiedProcess-in-0:
          destination: news-11-topic
        wordCountModifiedProcess-out-0:
          destination: news-11-count-topic
        wordCountHandler-in-0:
          destination: news-11-count-topic
        wordCountHandler-out-0:
          destination: news-21-count-topic

enable:
  comrade-kafka: false
  basic-kafka: false
  modified-kafka: true


